gText_Birch_Welcome::
	.string "Hello! Welcome to the world of\n"
	.string "POKéMON!\p"
	.string "My name is PROFESSOR BIRCH.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON.\n"
	.string "POKéMON are powerful, and can be\l"
	.string "dangerous in the wild, but they can be\l"
	.string "tamed and become loyal friends.\p"
	.string "Sometimes, we train by battling the\n"
	.string "POKéMON of other trainers, to\l"
	.string "strengthen and prepare ourselves.\l"
	.string "for the wilderness.\p"
	.string "We don't know everything about\n"
	.string "POKéMON. There are many secrets\l"
	.string "surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Okay, {PLAYER}{KUN}. Welcome to\n"
	.string "my hometown of LITTLEROOT.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
